version: "3.8"

services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony:rw
    working_dir: /var/www/symfony
    depends_on:
      - database
    networks:
      - symfony

  node:
    image: node:14
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    command: sh -c "npm install && npm run dev"
    networks:
      - symfony
  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    volumes:
      - ./:/var/www/symfony
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - symfony

  composer:
    image: composer:latest
    container_name: symfony_composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs --no-scripts --no-interaction --prefer-dist
    depends_on:
      - php
    networks:
      - symfony

  database:
    image: postgres:13
    container_name: postgres_database
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=symfony
    ports:
      - "5432:5432"
    networks:
      - symfony

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data: