version: "3.4"

# Configuration pour la production
services:
  php:
    build:
      target: app_php  # Mode production
    volumes:
      - ./:/srv/app:ro  # Code source en lecture seule
      - php_socket:/var/run/php
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      BREVO_API_KEY: ${BREVO_API_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}

  database:
    ports: []  # Pas d'exposition en production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  # Suppression des services de développement
  adminer:
    profiles: ["dev"]  # Disponible seulement en développement

  mailer:
    profiles: ["dev"]  # Disponible seulement en développement
