expose_php = 0
date.timezone = UTC
apc.enable_cli = 1
session.use_strict_mode = 1
session.save_path = /tmp/sessions
session.gc_maxlifetime = 3600
session.cookie_lifetime = 3600
session.cookie_httponly = 1
session.cookie_secure = 0
session.cookie_samesite = "Lax"
zend.detect_unicode = 0

; File upload settings
upload_max_filesize = 5M
post_max_size = 6M
max_file_uploads = 20

; https://symfony.com/doc/current/performance.html
realpath_cache_size = 4096K
realpath_cache_ttl = 600
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
opcache.enable_file_override = 1
